spring:
  application:
    name: product-manage-server

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:product-manage-server
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  springdoc:
    swagger-ui:
      path: /swagger-ui.html

  data:
    redis:
      host: 127.0.0.1
      port: 6379
